name: 'GitHub Actions echo'

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '*/6 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'echo'
        run: echo "Hello"
